version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - javanet

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafa
    networks:
      - javanet

  redis:
    image: redis
    networks:
      - javanet
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0.33
    container_name: segurosdb
    restart: always
    tty: true
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=segurosdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - javanet
    ports:
      - "3306:3306"

networks:
  javanet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.64.1/16

volumes:
  prometheus_data:
    driver: local