version: '3'

services:
  redis:
    image: redis
    networks:
      - javanet
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0.33
    command: --innodb-use-native-aio=0
    container_name: segurosdb
    restart: always
    tty: true
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=segurosdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - javanet
    ports:
      - "3306:3306"

networks:
  javanet:
    driver: bridge